### ISSUE TITLE
Test cellsWithThreeNeighboursWillSurvive

### ISSUE THREAD

**Issue by f-benz** [pfichtner/GameOfLife#2]
es wird der Fall getest, dass die Zellen zwei Nachbarn haben (im Gegensatz zum Methodennamen)

**Comment by pfichtner** [comment]
Du beziehst Dich auf https://github.com/pfichtner/GameOfLife/blob/acacd1d5452a6b0abaaf39f8f805bd2584b345b9/src/test/java/gol/GoLTest.java#L36 nehme ich an? Richtig, habe den Test nachträglich geändert, er hat ursprünglich das Überleben mit drei Nachbarn verifiziert, das tut er jetzt tatsächlich nicht mehr. Will fix

**Comment by f-benz** [comment]
ja - ich habe einen entsprechenden Pull Request gemacht

**Comment by pfichtner** [comment]
Habe meinen alten Test aus der Historie wieder zurück geholt. Was war Deine Absicht mit den jeweils zwei extra Reihen und Spalten?

**Comment by f-benz** [comment]
Okay :-)
(Es hatte keinen besonderen Hintergrund, außer dass es dann keine "Randfälle" sind.)
